// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package pbgame

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoadRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadRequest) Reset()         { *m = LoadRequest{} }
func (m *LoadRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()    {}
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_729622b71917d163, []int{0}
}
func (m *LoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRequest.Unmarshal(m, b)
}
func (m *LoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRequest.Marshal(b, m, deterministic)
}
func (dst *LoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRequest.Merge(dst, src)
}
func (m *LoadRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRequest.Size(m)
}
func (m *LoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRequest proto.InternalMessageInfo

func (m *LoadRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type LoadResponse struct {
	Result               ErrorCode `protobuf:"varint,1,opt,name=result,enum=pbgame.ErrorCode" json:"result,omitempty"`
	Uid                  uint32    `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Money                int32     `protobuf:"varint,4,opt,name=money" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoadResponse) Reset()         { *m = LoadResponse{} }
func (m *LoadResponse) String() string { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()    {}
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_729622b71917d163, []int{1}
}
func (m *LoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadResponse.Unmarshal(m, b)
}
func (m *LoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadResponse.Marshal(b, m, deterministic)
}
func (dst *LoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadResponse.Merge(dst, src)
}
func (m *LoadResponse) XXX_Size() int {
	return xxx_messageInfo_LoadResponse.Size(m)
}
func (m *LoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadResponse proto.InternalMessageInfo

func (m *LoadResponse) GetResult() ErrorCode {
	if m != nil {
		return m.Result
	}
	return ErrorCode_SUCCESS
}

func (m *LoadResponse) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoadResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoadResponse) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

type SaveRequest struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Money                int32    `protobuf:"varint,3,opt,name=money" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_729622b71917d163, []int{2}
}
func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (dst *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(dst, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SaveRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SaveRequest) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

type SaveResponse struct {
	Result               ErrorCode `protobuf:"varint,1,opt,name=result,enum=pbgame.ErrorCode" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_729622b71917d163, []int{3}
}
func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (dst *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(dst, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetResult() ErrorCode {
	if m != nil {
		return m.Result
	}
	return ErrorCode_SUCCESS
}

type CreatePlayerRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Money                int32    `protobuf:"varint,3,opt,name=money" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlayerRequest) Reset()         { *m = CreatePlayerRequest{} }
func (m *CreatePlayerRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePlayerRequest) ProtoMessage()    {}
func (*CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_729622b71917d163, []int{4}
}
func (m *CreatePlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayerRequest.Unmarshal(m, b)
}
func (m *CreatePlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayerRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayerRequest.Merge(dst, src)
}
func (m *CreatePlayerRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePlayerRequest.Size(m)
}
func (m *CreatePlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayerRequest proto.InternalMessageInfo

func (m *CreatePlayerRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CreatePlayerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePlayerRequest) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

type CreatePlayerResponse struct {
	Result               ErrorCode `protobuf:"varint,1,opt,name=result,enum=pbgame.ErrorCode" json:"result,omitempty"`
	Uid                  uint32    `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreatePlayerResponse) Reset()         { *m = CreatePlayerResponse{} }
func (m *CreatePlayerResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePlayerResponse) ProtoMessage()    {}
func (*CreatePlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_729622b71917d163, []int{5}
}
func (m *CreatePlayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayerResponse.Unmarshal(m, b)
}
func (m *CreatePlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayerResponse.Marshal(b, m, deterministic)
}
func (dst *CreatePlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayerResponse.Merge(dst, src)
}
func (m *CreatePlayerResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePlayerResponse.Size(m)
}
func (m *CreatePlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayerResponse proto.InternalMessageInfo

func (m *CreatePlayerResponse) GetResult() ErrorCode {
	if m != nil {
		return m.Result
	}
	return ErrorCode_SUCCESS
}

func (m *CreatePlayerResponse) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func init() {
	proto.RegisterType((*LoadRequest)(nil), "pbgame.LoadRequest")
	proto.RegisterType((*LoadResponse)(nil), "pbgame.LoadResponse")
	proto.RegisterType((*SaveRequest)(nil), "pbgame.SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "pbgame.SaveResponse")
	proto.RegisterType((*CreatePlayerRequest)(nil), "pbgame.CreatePlayerRequest")
	proto.RegisterType((*CreatePlayerResponse)(nil), "pbgame.CreatePlayerResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DBClient is the client API for DB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DBClient interface {
	LoadPlayer(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error)
	SavePlayer(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	CreatePlayer(ctx context.Context, in *CreatePlayerRequest, opts ...grpc.CallOption) (*CreatePlayerResponse, error)
}

type dBClient struct {
	cc *grpc.ClientConn
}

func NewDBClient(cc *grpc.ClientConn) DBClient {
	return &dBClient{cc}
}

func (c *dBClient) LoadPlayer(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, "/pbgame.DB/LoadPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) SavePlayer(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, "/pbgame.DB/SavePlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) CreatePlayer(ctx context.Context, in *CreatePlayerRequest, opts ...grpc.CallOption) (*CreatePlayerResponse, error) {
	out := new(CreatePlayerResponse)
	err := c.cc.Invoke(ctx, "/pbgame.DB/CreatePlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBServer is the server API for DB service.
type DBServer interface {
	LoadPlayer(context.Context, *LoadRequest) (*LoadResponse, error)
	SavePlayer(context.Context, *SaveRequest) (*SaveResponse, error)
	CreatePlayer(context.Context, *CreatePlayerRequest) (*CreatePlayerResponse, error)
}

func RegisterDBServer(s *grpc.Server, srv DBServer) {
	s.RegisterService(&_DB_serviceDesc, srv)
}

func _DB_LoadPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).LoadPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbgame.DB/LoadPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).LoadPlayer(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_SavePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).SavePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbgame.DB/SavePlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).SavePlayer(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_CreatePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).CreatePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbgame.DB/CreatePlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).CreatePlayer(ctx, req.(*CreatePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbgame.DB",
	HandlerType: (*DBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadPlayer",
			Handler:    _DB_LoadPlayer_Handler,
		},
		{
			MethodName: "SavePlayer",
			Handler:    _DB_SavePlayer_Handler,
		},
		{
			MethodName: "CreatePlayer",
			Handler:    _DB_CreatePlayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db.proto",
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_db_729622b71917d163) }

var fileDescriptor_db_729622b71917d163 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x31, 0x4f, 0x83, 0x50,
	0x10, 0xc7, 0xfb, 0xa0, 0x45, 0x3d, 0xd0, 0xe8, 0x95, 0x81, 0xa0, 0x03, 0x79, 0x8b, 0xb8, 0x30,
	0xd4, 0xa9, 0xab, 0xd5, 0xc1, 0xe8, 0x60, 0xe8, 0xe4, 0xf8, 0x28, 0x17, 0x63, 0x52, 0x78, 0xf8,
	0x00, 0x93, 0x7e, 0x42, 0xbf, 0x96, 0x81, 0x57, 0x22, 0x55, 0x12, 0xd3, 0xa4, 0xdb, 0xbb, 0xe3,
	0x7f, 0xbf, 0xbb, 0xfb, 0x1f, 0x70, 0x9c, 0x26, 0x51, 0xa1, 0x64, 0x25, 0xd1, 0x2a, 0x92, 0x37,
	0x91, 0x91, 0x6f, 0x93, 0x52, 0x52, 0xe9, 0x24, 0xbf, 0x06, 0xfb, 0x59, 0x8a, 0x34, 0xa6, 0x8f,
	0x9a, 0xca, 0x0a, 0x3d, 0x38, 0x12, 0xab, 0x95, 0xac, 0xf3, 0xca, 0x63, 0x01, 0x0b, 0x4f, 0xe2,
	0x2e, 0xe4, 0x35, 0x38, 0x5a, 0x58, 0x16, 0x32, 0x2f, 0x09, 0x6f, 0xc0, 0x52, 0x54, 0xd6, 0x6b,
	0x2d, 0x3c, 0x9b, 0x5d, 0x44, 0x1a, 0x1f, 0x3d, 0x34, 0xf4, 0x85, 0x4c, 0x29, 0xde, 0x0a, 0xf0,
	0x1c, 0xcc, 0xfa, 0x3d, 0xf5, 0x8c, 0x80, 0x85, 0xa7, 0x71, 0xf3, 0x44, 0x84, 0x71, 0x2e, 0x32,
	0xf2, 0xcc, 0xb6, 0x47, 0xfb, 0x46, 0x17, 0x26, 0x99, 0xcc, 0x69, 0xe3, 0x8d, 0x03, 0x16, 0x4e,
	0x62, 0x1d, 0xf0, 0x47, 0xb0, 0x97, 0xe2, 0x93, 0xba, 0xf9, 0xb6, 0x28, 0xf6, 0x17, 0x65, 0x0c,
	0xa1, 0xcc, 0x3e, 0x6a, 0x0e, 0x8e, 0x46, 0xed, 0xbd, 0x01, 0x7f, 0x85, 0xe9, 0x42, 0x91, 0xa8,
	0xe8, 0x65, 0x2d, 0x36, 0xa4, 0xfe, 0x75, 0x6b, 0x8f, 0xa9, 0x96, 0xe0, 0xee, 0xa2, 0x0f, 0xe0,
	0xef, 0xec, 0x8b, 0x81, 0x71, 0x7f, 0x87, 0x73, 0x80, 0xe6, 0x66, 0x9a, 0x8c, 0xd3, 0x8e, 0xd0,
	0x3b, 0xb8, 0xef, 0xee, 0x26, 0x75, 0x73, 0x3e, 0x6a, 0x4a, 0x1b, 0xb3, 0x7e, 0x97, 0xf6, 0x6e,
	0xf1, 0x53, 0xda, 0x77, 0x95, 0x8f, 0xf0, 0x09, 0x9c, 0xfe, 0x46, 0x78, 0xd9, 0xe9, 0x06, 0x2c,
	0xf4, 0xaf, 0x86, 0x3f, 0x76, 0xb0, 0xc4, 0x6a, 0x7f, 0xd3, 0xdb, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xcd, 0xe0, 0xcb, 0xe8, 0xc7, 0x02, 0x00, 0x00,
}
