// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package pbgame

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_f7dcc7f0e401fff7, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	ErrorCode            ErrorCode `protobuf:"varint,1,opt,name=errorCode,enum=pbgame.ErrorCode" json:"errorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_f7dcc7f0e401fff7, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_SUCCESS
}

type PlayerDataMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDataMsg) Reset()         { *m = PlayerDataMsg{} }
func (m *PlayerDataMsg) String() string { return proto.CompactTextString(m) }
func (*PlayerDataMsg) ProtoMessage()    {}
func (*PlayerDataMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_f7dcc7f0e401fff7, []int{2}
}
func (m *PlayerDataMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDataMsg.Unmarshal(m, b)
}
func (m *PlayerDataMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDataMsg.Marshal(b, m, deterministic)
}
func (dst *PlayerDataMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDataMsg.Merge(dst, src)
}
func (m *PlayerDataMsg) XXX_Size() int {
	return xxx_messageInfo_PlayerDataMsg.Size(m)
}
func (m *PlayerDataMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDataMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDataMsg proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LoginRequest)(nil), "pbgame.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pbgame.LoginResponse")
	proto.RegisterType((*PlayerDataMsg)(nil), "pbgame.PlayerDataMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoginClient is the client API for Login service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type loginClient struct {
	cc *grpc.ClientConn
}

func NewLoginClient(cc *grpc.ClientConn) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/pbgame.Login/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServer is the server API for Login service.
type LoginServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterLoginServer(s *grpc.Server, srv LoginServer) {
	s.RegisterService(&_Login_serviceDesc, srv)
}

func _Login_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbgame.Login/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Login_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbgame.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Login_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login.proto",
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_login_f7dcc7f0e401fff7) }

var fileDescriptor_login_f7dcc7f0e401fff7 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x48, 0x4a, 0x4f, 0xcc, 0x4d, 0x95,
	0xe2, 0x4e, 0x2d, 0x2a, 0xca, 0x2f, 0x82, 0x08, 0x2a, 0xb9, 0x70, 0xf1, 0xf8, 0x80, 0xd4, 0x04,
	0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x70, 0xb1, 0x27, 0x26, 0x27, 0xe7, 0x97, 0xe6,
	0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x42, 0x52, 0x5c, 0x1c, 0x05, 0x89,
	0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12, 0x4c, 0x60, 0x29, 0x38, 0x5f, 0xc9, 0x81, 0x8b, 0x17,
	0x6a, 0x4a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x3e, 0x17, 0x27, 0xd8, 0x16, 0xe7, 0xfc,
	0x94, 0x54, 0xb0, 0x41, 0x7c, 0x46, 0x82, 0x7a, 0x10, 0xfb, 0xf5, 0x5c, 0x61, 0x12, 0x41, 0x08,
	0x35, 0x4a, 0xfc, 0x5c, 0xbc, 0x01, 0x39, 0x89, 0x95, 0xa9, 0x45, 0x2e, 0x89, 0x25, 0x89, 0xbe,
	0xc5, 0xe9, 0x46, 0xf6, 0x5c, 0xac, 0x60, 0x23, 0x85, 0xcc, 0x60, 0x0c, 0x11, 0x98, 0x01, 0xc8,
	0x0e, 0x96, 0x12, 0x45, 0x13, 0x85, 0x38, 0x40, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x41, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0xfb, 0x6c, 0x18, 0x04, 0x01, 0x00, 0x00,
}
