// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package pbgame

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnterGameRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterGameRequest) Reset()         { *m = EnterGameRequest{} }
func (m *EnterGameRequest) String() string { return proto.CompactTextString(m) }
func (*EnterGameRequest) ProtoMessage()    {}
func (*EnterGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_8901261e1d6986e7, []int{0}
}
func (m *EnterGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGameRequest.Unmarshal(m, b)
}
func (m *EnterGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGameRequest.Marshal(b, m, deterministic)
}
func (dst *EnterGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGameRequest.Merge(dst, src)
}
func (m *EnterGameRequest) XXX_Size() int {
	return xxx_messageInfo_EnterGameRequest.Size(m)
}
func (m *EnterGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGameRequest proto.InternalMessageInfo

func (m *EnterGameRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type EnterGameResponse struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Money                int32    `protobuf:"varint,3,opt,name=money" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterGameResponse) Reset()         { *m = EnterGameResponse{} }
func (m *EnterGameResponse) String() string { return proto.CompactTextString(m) }
func (*EnterGameResponse) ProtoMessage()    {}
func (*EnterGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_8901261e1d6986e7, []int{1}
}
func (m *EnterGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGameResponse.Unmarshal(m, b)
}
func (m *EnterGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGameResponse.Marshal(b, m, deterministic)
}
func (dst *EnterGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGameResponse.Merge(dst, src)
}
func (m *EnterGameResponse) XXX_Size() int {
	return xxx_messageInfo_EnterGameResponse.Size(m)
}
func (m *EnterGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGameResponse proto.InternalMessageInfo

func (m *EnterGameResponse) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *EnterGameResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnterGameResponse) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

type RollRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollRequest) Reset()         { *m = RollRequest{} }
func (m *RollRequest) String() string { return proto.CompactTextString(m) }
func (*RollRequest) ProtoMessage()    {}
func (*RollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_8901261e1d6986e7, []int{2}
}
func (m *RollRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollRequest.Unmarshal(m, b)
}
func (m *RollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollRequest.Marshal(b, m, deterministic)
}
func (dst *RollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollRequest.Merge(dst, src)
}
func (m *RollRequest) XXX_Size() int {
	return xxx_messageInfo_RollRequest.Size(m)
}
func (m *RollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollRequest proto.InternalMessageInfo

type RollResponse struct {
	Win                  int32    `protobuf:"varint,1,opt,name=win" json:"win,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollResponse) Reset()         { *m = RollResponse{} }
func (m *RollResponse) String() string { return proto.CompactTextString(m) }
func (*RollResponse) ProtoMessage()    {}
func (*RollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_8901261e1d6986e7, []int{3}
}
func (m *RollResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollResponse.Unmarshal(m, b)
}
func (m *RollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollResponse.Marshal(b, m, deterministic)
}
func (dst *RollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollResponse.Merge(dst, src)
}
func (m *RollResponse) XXX_Size() int {
	return xxx_messageInfo_RollResponse.Size(m)
}
func (m *RollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollResponse proto.InternalMessageInfo

func (m *RollResponse) GetWin() int32 {
	if m != nil {
		return m.Win
	}
	return 0
}

func init() {
	proto.RegisterType((*EnterGameRequest)(nil), "pbgame.EnterGameRequest")
	proto.RegisterType((*EnterGameResponse)(nil), "pbgame.EnterGameResponse")
	proto.RegisterType((*RollRequest)(nil), "pbgame.RollRequest")
	proto.RegisterType((*RollResponse)(nil), "pbgame.RollResponse")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_game_8901261e1d6986e7) }

var fileDescriptor_game_8901261e1d6986e7 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0x86, 0x31, 0xd3, 0x68, 0x4a, 0xb0, 0xa5, 0xc3, 0x1e, 0x65, 0x4f, 0x1e, 0xa2, 0x4b, 0xcf,
	0x10, 0x1d, 0x83, 0x79, 0x83, 0xd5, 0x86, 0x10, 0xdc, 0x19, 0xd3, 0x95, 0xe8, 0xed, 0xc3, 0xb5,
	0xa8, 0xdb, 0xf7, 0xc1, 0x3f, 0xff, 0xfc, 0x00, 0x77, 0xeb, 0xe8, 0xd8, 0xf5, 0xe2, 0x45, 0xa5,
	0x5d, 0x35, 0x99, 0x39, 0x40, 0x7e, 0x66, 0x4f, 0xfd, 0xc5, 0x3a, 0x42, 0x7a, 0x8c, 0x34, 0x78,
	0xa5, 0x61, 0x65, 0xeb, 0x5a, 0x46, 0xf6, 0x3a, 0x2a, 0xa2, 0x72, 0x8d, 0x5f, 0x35, 0x57, 0xd8,
	0xfd, 0xa5, 0x87, 0x4e, 0x78, 0x20, 0x95, 0x43, 0x3c, 0x36, 0xb7, 0x10, 0xcd, 0x70, 0x42, 0xa5,
	0x60, 0xc9, 0xd6, 0x91, 0x5e, 0x84, 0xeb, 0xc0, 0x6a, 0x0f, 0x89, 0x13, 0xa6, 0x97, 0x8e, 0x8b,
	0xa8, 0x4c, 0x70, 0x16, 0x93, 0xc1, 0x06, 0xa5, 0x6d, 0x3f, 0x9f, 0x4d, 0x01, 0xdb, 0x59, 0x7f,
	0xd5, 0xcf, 0x86, 0x43, 0x75, 0x82, 0x13, 0x56, 0x69, 0x98, 0x7f, 0x7a, 0x07, 0x00, 0x00, 0xff,
	0xff, 0xfa, 0xe4, 0x0e, 0xfe, 0xcc, 0x00, 0x00, 0x00,
}
