// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manager.proto

package pbgame

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Server struct {
	Id                   uint32   `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=addr" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_27134d7202087a63, []int{0}
}
func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (dst *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(dst, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Server) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Server) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type ServerListReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Server               *Server  `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerListReq) Reset()         { *m = ServerListReq{} }
func (m *ServerListReq) String() string { return proto.CompactTextString(m) }
func (*ServerListReq) ProtoMessage()    {}
func (*ServerListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_27134d7202087a63, []int{1}
}
func (m *ServerListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerListReq.Unmarshal(m, b)
}
func (m *ServerListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerListReq.Marshal(b, m, deterministic)
}
func (dst *ServerListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerListReq.Merge(dst, src)
}
func (m *ServerListReq) XXX_Size() int {
	return xxx_messageInfo_ServerListReq.Size(m)
}
func (m *ServerListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ServerListReq proto.InternalMessageInfo

func (m *ServerListReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ServerListReq) GetServer() *Server {
	if m != nil {
		return m.Server
	}
	return nil
}

type ServerListRsp struct {
	Server               []*Server `protobuf:"bytes,1,rep,name=server" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServerListRsp) Reset()         { *m = ServerListRsp{} }
func (m *ServerListRsp) String() string { return proto.CompactTextString(m) }
func (*ServerListRsp) ProtoMessage()    {}
func (*ServerListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_27134d7202087a63, []int{2}
}
func (m *ServerListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerListRsp.Unmarshal(m, b)
}
func (m *ServerListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerListRsp.Marshal(b, m, deterministic)
}
func (dst *ServerListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerListRsp.Merge(dst, src)
}
func (m *ServerListRsp) XXX_Size() int {
	return xxx_messageInfo_ServerListRsp.Size(m)
}
func (m *ServerListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ServerListRsp proto.InternalMessageInfo

func (m *ServerListRsp) GetServer() []*Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func init() {
	proto.RegisterType((*Server)(nil), "pbgame.Server")
	proto.RegisterType((*ServerListReq)(nil), "pbgame.ServerListReq")
	proto.RegisterType((*ServerListRsp)(nil), "pbgame.ServerListRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerClient interface {
	GetServerList(ctx context.Context, in *ServerListReq, opts ...grpc.CallOption) (*ServerListRsp, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) GetServerList(ctx context.Context, in *ServerListReq, opts ...grpc.CallOption) (*ServerListRsp, error) {
	out := new(ServerListRsp)
	err := c.cc.Invoke(ctx, "/pbgame.Manager/GetServerList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServer is the server API for Manager service.
type ManagerServer interface {
	GetServerList(context.Context, *ServerListReq) (*ServerListRsp, error)
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_GetServerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetServerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbgame.Manager/GetServerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetServerList(ctx, req.(*ServerListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbgame.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerList",
			Handler:    _Manager_GetServerList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager.proto",
}

func init() { proto.RegisterFile("manager.proto", fileDescriptor_manager_27134d7202087a63) }

var fileDescriptor_manager_27134d7202087a63 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0xcc, 0x4b,
	0x4c, 0x4f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x48, 0x4a, 0x4f, 0xcc,
	0x4d, 0x55, 0x72, 0xe0, 0x62, 0x0b, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x12, 0xe2, 0xe3, 0x62, 0xca,
	0x4c, 0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0x29,
	0xa9, 0x2c, 0x48, 0x95, 0x60, 0x06, 0x8b, 0x80, 0xd9, 0x20, 0xb1, 0xc4, 0x94, 0x94, 0x22, 0x09,
	0x16, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0xc9, 0x97, 0x8b, 0x17, 0x62, 0x82, 0x4f, 0x66,
	0x71, 0x49, 0x50, 0x6a, 0xa1, 0x90, 0x08, 0x17, 0x6b, 0x49, 0x7e, 0x76, 0x6a, 0x9e, 0x04, 0x23,
	0x58, 0x15, 0x84, 0x23, 0xa4, 0xc6, 0xc5, 0x56, 0x0c, 0x56, 0x06, 0xb6, 0x82, 0xdb, 0x88, 0x4f,
	0x0f, 0xe2, 0x02, 0x3d, 0x88, 0xe6, 0x20, 0xa8, 0xac, 0x92, 0x39, 0x8a, 0x71, 0xc5, 0x05, 0x48,
	0x1a, 0x19, 0x15, 0x98, 0x71, 0x6b, 0x34, 0xf2, 0xe2, 0x62, 0xf7, 0x85, 0x78, 0x51, 0xc8, 0x9e,
	0x8b, 0xd7, 0x3d, 0xb5, 0x04, 0x61, 0x8c, 0x90, 0x28, 0xaa, 0x1e, 0xa8, 0x4b, 0xa5, 0xb0, 0x09,
	0x17, 0x17, 0x28, 0x31, 0x24, 0xb1, 0x81, 0x03, 0xc9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x54,
	0x7a, 0x47, 0xb0, 0x35, 0x01, 0x00, 0x00,
}
